CREATE PROCEDURE FI_SP_IncBeneficiario
    @NOME NVARCHAR(255),
    @CPF CHAR(11),
    @IDCLIENTE BIGINT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE)
    VALUES (@NOME, @CPF, @IDCLIENTE);
    
	SELECT SCOPE_IDENTITY()
END